Major updates to knife.rb and bootstrap script.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,44 +1,55 @@
 #!/usr/bin/env bash
+set -e
+[ -n "$BOOTSTRAP_DEBUG" ] && set -x
 
-log()   { printf -- "-----> $*\n" ; return $? ; }
-warn()  { printf -- ">>> $*\n" ; return $? ; }
-fail()  { printf -- "\nERROR: $*\n" ; exit 1 ; }
+banner()  { printf -- "-----> $*\n"; }
+log()     { printf -- "       $*\n"; }
+warn()    { printf -- ">>>>>> $*\n"; }
+fail()    { printf -- "\nERROR: $*\n" ; exit 1 ; }
 
 if ! command -v direnv >/dev/null ; then
-  if [ "$(uname)" == "Darwin" ] && command -v brew >/dev/null ; then
-    log "Direnv package missing, installing from homebrew"
-    brew install direnv
-    eval $(direnv hook $SHELL)
-  else
-    warn "The direnv command is not installed and helps in configuring"
-    warn "this Chef repository."
-    warn ""
-    warn "Please visit https://github.com/zimbatm/direnv for more details."
-  fi
+  warn "The direnv command is not installed and helps in using"
+  warn "this project."
+  warn ""
+  warn "Please visit https://github.com/zimbatm/direnv for more details."
+  warn ""
+  warn "If you are on a mac and using homebrew, install it with:"
+  warn ""
+  warn "    $ brew install direnv"
+  warn ""
+  warn "Follow the post-install instructions, and re-run $0"
+  warn "\n"
 fi
 
 if ! command -v bundle >/dev/null ; then
-  log "Installing bundler gem"
+  banner "Installing bundler gem"
   gem install bundler
 fi
 
-log "Running bundle"
-bundle install --binstubs --path vendor/bundle
-
-if [ ! -d "$HOME/.chef.d" ] ; then
-  log "Creating $HOME/.chef.d directory"
-  mkdir -p "$HOME/.chef.d"
-fi
+bundle_cmd="bundle install --path vendor/bundle --binstubs vendor/binstubs"
+banner "Running '$bundle_cmd'"
+$bundle_cmd
 
 if [ ! -f "$(dirname $0)/../.envrc" ] ; then
-  log "Creating .envrc"
-  printf "Enter your organization or group name, something like 'widgetco' or 'personal'.\n"
+  banner "Creating .envrc"
+  printf "Enter the logical name for your chef server (FQDN perhaps?)\n"
   printf "name> "
   read NAME
 
-  if [ ! -f "$HOME/.chef.d/$NAME-env.sh" ] ; then
-    log "Creating $HOME/.chef.d/$NAME-env.sh (please edit afterwards)"
-    cat <<_END_OF_ENV > "$HOME/.chef.d/$NAME-env.sh"
+  env_sh="$HOME/.chef.d/$NAME/env.sh"
+
+  if [ ! -d "$(dirname $env_sh)" ] ; then
+    log "Creating $(dirname $env_sh) directory"
+    mkdir -p "$(dirname $env_sh)"
+  fi
+
+  if [ ! -f "$env_sh" ] ; then
+    log "Creating $env_sh (please edit afterwards)"
+    cat <<_END_OF_ENV > "$env_sh"
+export KNIFE_CHEF_SERVER_URL=""
+export KNIFE_VALIDATION_KEY="\$HOME/.chef.d/$NAME/validation.pem"
+export KNIFE_CLIENT_KEY="\$HOME/.chef.d/$NAME/$USER.pem"
+
 export AWS_AWS_ACCESS_KEY_ID=""
 export AWS_AWS_SECRET_ACCESS_KEY=""
 export AWS_AWS_SSH_KEY_ID=""
@@ -55,20 +66,12 @@ export BLUEBOX_API_KEY=""
 _END_OF_ENV
   fi
 
-  if [ ! -f "$HOME/.chef.d/$NAME-env-user.sh" ] ; then
-    log "Creating $HOME/.chef.d/$NAME-env-user.sh (please edit afterwards)"
-    cat <<_END_OF_ENV > "$HOME/.chef.d/$NAME-env-user.sh"
-export KNIFE_USER="$USER"
-_END_OF_ENV
-  fi
-
   cat <<_END_OF_ENVRC > "$(dirname $0)/../.envrc"
 PATH_add script
-PATH_add bin
+PATH_add vendor/binstubs
 
 # load knife config vars
-knife_config=""
-for config in \$HOME/.chef.d/$NAME-env.sh \$HOME/.chef.d/$NAME-env-*.sh ; do
+for config in \$HOME/.chef.d/$NAME/env.sh \$HOME/.chef.d/$NAME/env-*.sh ; do
   if [ -f "\$config" ] ; then
     echo "direnv: loading \$config"
     eval \$(cat \$config)
@@ -80,5 +83,7 @@ _END_OF_ENVRC
   touch "$(dirname $0)/../.envrc"
 fi
 
-log "Running Berkshelf"
-"$(dirname $0)/../bin/berks" install
+banner "Running Berkshelf"
+"$(dirname $0)/../vendor/binstubs/berks" install
+
+banner 'All ready!'
